### ISSUE TITLE
Invalid filenameが発生する原因の大まかな理由の表示が欲しい。

### ISSUE THREAD

**Issue by kazumori102** [illustcollector/nijie-downloader#9]
「Invalid filename」だけではあまりにも具体性が無く対応のしようがない。

私がDLしようとした際の設定は以下の通り。何が原因でしょうか。
単数${title}${userName}
複数${title}${userName}-${page}

DL対象はこれ
https://nijie.info/view.php?id=427126

**Comment by illustcollector** [comment]
修正しました。
原因はダウンロードフォルダ直下に保存することを想定していなかったためでした。
現在はv1.1の審査中でその間は更新することができないため、
v1.1が公開された後に修正版に更新いたします。
情報の揃った不具合報告助かります。ありがとうございました。

**Comment by NaokiSato102** [comment]
了解です。ご丁寧にありがとうございました。
